source 'https://github.com/CocoaPods/Specs.git'

target 'enhance' do
  pod "enhance", :path => "../"

    target 'Tests' do
      inherit! :search_paths

      pod 'Specta', '~> 1.0'
      pod 'Expecta', '~> 1.0'
      pod 'FBSnapshotTestCase'
      pod 'Expecta+Snapshots'
    end
end
