osx_image: xcode7.3
language: objective-c
podfile: Example/Podfile
cache:
  - cocoapods
script:
- set -o pipefail && xcodebuild -workspace Example/enhance.xcworkspace -scheme Tests -configuration Debug clean build test -sdk iphonesimulator -destination platform="iOS Simulator,OS=latest,name=iPhone 6" | xcpretty -c
